version: "3.8"
services:
  ripe-updater:
    restart: always
    build:
        context: ./ripe-updater
        dockerfile: Dockerfile
    env_file:
      - .env.updater
    ports:
      - "${UPDATER_HTTP_PORT}:80"
    networks:
      - ripe-updater
    volumes:
        - "${RIPE_TEMPLATE_DIR}:/opt/ripeupdater/templates:ro"
    depends_on:
      - minio

  minio:
    restart: always
    image: docker.io/bitnami/minio:2024
    environment:
      MINIO_ROOT_USER: CjGb9PDkjQqMi6V
      MINIO_ROOT_PASSWORD: 8s82NHXq6pPsJAP4S
      MINIO_DEFAULT_BUCKETS: ripe-backups
    volumes:
      - "minio-data:/bitnami/minio/data"
    networks:
      - ripe-updater

networks:
    ripe-updater:
        driver: bridge

volumes:
    minio-data:
        driver: local


